create database raipur;
use raipur;
DROP DATABASE RAIPUR;
show databases;

CREATE TABLE CITY(
C_ID INT PRIMARY KEY,
C_NAME VARCHAR(50),
C_AREA VARCHAR(50) NOT NULL,
C_CODE INT NOT NULL
);
DROP TABLE CITY;
CREATE DATABASE IF NOT EXISTS CITY; 
DROP DATABASE IF EXISTS CITY;
SHOW DATABASES;
SHOW TABLES;
DESCRIBE CITY;



INSERT INTO CITY (C_ID,C_NAME,C_AREA,C_CODE) VALUES
(01,"DURG","ABC",101),
(02,"DHAMTARI","DEF",202),
(03,"BHILAI","GHI",303);
SELECT * FROM CITY;
